apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-proxy-dev
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/political-sphere/platform.git
    targetRevision: HEAD
    path: charts/db-proxy
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
