apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    platform.political-sphere.io/environment: ci
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ci-allow-argocd
  namespace: ci
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              platform.political-sphere.io/environment: ci
  policyTypes:
    - Ingress
