name: "Setup Node.js with Dependencies"
description: "Setup Node.js and install dependencies with caching"
author: "Political Sphere"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22"

  cache:
    description: "Enable dependency caching (npm|yarn|pnpm|none)"
    required: false
    default: "npm"

  install-command:
    description: "Command to install dependencies"
    required: false
    default: "npm ci"

outputs:
  node-version:
    description: "Resolved Node.js version"
    value: ${{ steps.setup-node.outputs.node-version }}

  cache-hit:
    description: "Whether cache was hit"
    value: ${{ steps.setup-node.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      shell: bash
      env:
        INSTALL_COMMAND: ${{ inputs.install-command }}
      run: |
        echo "📦 Installing dependencies..."
        "$INSTALL_COMMAND"
        echo "✅ Dependencies installed successfully"

    - name: Verify installation
      shell: bash
      run: |
        echo "🔍 Verifying Node.js and npm versions..."
        node --version
        npm --version
        echo "✅ Environment ready"
