name: gitleaks-scan

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks scan
        run: |
          chmod +x scripts/security/gitleaks-scan.sh
          ./scripts/security/gitleaks-scan.sh

      - name: Upload gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: artifacts/gitleaks-report.json

      - name: Comment on PR with findings
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = 'artifacts/gitleaks-report.json';
            if (!fs.existsSync(path)) return;
            const report = JSON.parse(fs.readFileSync(path, 'utf8'));
            if (!report || report.length === 0) return;
            const lines = report.map(r => `- file: ${r.Path} rule: ${r.Rule}`);
            const body = `⚠️ Gitleaks found potential secrets in this PR:\n\n${lines.join('\n')}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body,
            });
