name: build-and-test

on:
  workflow_call:
    inputs:
      node_version:
        description: Node.js version to use
        type: string
        default: "20"
      services:
        description: Comma delimited list of Nx projects to build (e.g. "api,frontend")
        type: string
        default: "api"
      dockerfile:
        description: Path to Dockerfile relative to repo root
        type: string
        default: "apps/api/Dockerfile"
      image_name:
        description: Image name (repository portion only)
        type: string
        default: "api"
      working_directory:
        description: Path to repository working directory
        type: string
        default: "."
      enable_trivy:
        description: Run Trivy scan on built image
        type: boolean
        default: true
      pnpm_cache:
        description: Enable pnpm cache (true/false)
        type: boolean
        default: true
    secrets:
      aws_role_to_assume:
        required: false
        description: IAM role to assume via OIDC for ECR access
      aws_region:
        required: false
        description: AWS region for registry operations
      ecr_registry:
        required: false
        description: Full ECR registry URI (e.g. 123.dkr.ecr.us-east-1.amazonaws.com)

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    env:
      SERVICES: ${{ inputs.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: ${{ inputs.pnpm_cache && 'pnpm' || 'npm' }}

      - name: Install dependencies
        run: npm ci

      - name: Cache Nx build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .nx/cache
            node_modules/.cache/nx
          key: ${{ runner.os }}-nx-${{ hashFiles('**/project.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Run lint
        run: npx nx affected --target=lint --base=origin/main --head=$GITHUB_SHA || npx nx run-many --target=lint --projects=${SERVICES//,/ }

      - name: Run tests
        run: npx nx run-many --target=test --projects=${SERVICES//,/ }

      - name: Run integration tests
        run: npm run test:integration

      - name: Check coverage threshold
        run: |
          npx nx run-many --target=test --projects=${SERVICES//,/ } --coverage
          npx nyc check-coverage --lines 80 --functions 80 --branches 80 --statements 80

      - name: Build applications
        run: npx nx run-many --target=build --projects=${SERVICES//,/ }

      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-file sbom.json

      - name: Configure AWS credentials
        if: secrets.aws_role_to_assume != ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: ${{ secrets.aws_region || 'us-east-1' }}

      - name: Login to Amazon ECR
        if: secrets.aws_role_to_assume != ''
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ secrets.ecr_registry }}
          REPO_OWNER: ${{ github.repository_owner }}
          IMAGE_NAME: ${{ inputs.image_name }}
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          IMAGE_TAG=${GITHUB_SHA::12}
          IMAGE_URI=${ECR_REGISTRY:-${REPO_OWNER}/${IMAGE_NAME}}:${IMAGE_TAG}
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV
          docker build -t "${IMAGE_URI}" -f "${DOCKERFILE}" .

      - name: Trivy scan
        if: inputs.enable_trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_URI }}
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Push image
        if: secrets.aws_role_to_assume != ''
        run: docker push ${{ env.IMAGE_URI }}

      - name: Persist image tag artifact
        if: env.IMAGE_URI != ''
        run: echo "${IMAGE_URI}" > image-uri.txt

      - name: Upload image tag
        if: env.IMAGE_URI != ''
        uses: actions/upload-artifact@v4
        with:
          name: image-uri
          path: image-uri.txt
