name: Copilot Experiment Monthly Summary

on:
  schedule:
    # Run on the 1st of every month at 9 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate monthly summary
        run: npm run ai:copilot-log summary

      - name: Create issue with summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const now = new Date();
            const month = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

            const summaryPath = path.join('ai-logs', `copilot-summary-${month}.json`);

            if (fs.existsSync(summaryPath)) {
              const summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));

              const issueBody = `
            ## Copilot Experiment Summary - ${month}

            ### Overview
            - **Total Experiments:** ${summary.totalExperiments}
            - **Unique Prompt Variants:** ${Object.keys(summary.promptVariants).length}

            ### Outcomes Distribution
            ${Object.entries(summary.outcomes).map(([outcome, count]) => `- ${outcome}: ${count}`).join('\n')}

            ### Prompt Variant Performance
            ${Object.entries(summary.promptVariants).map(([variant, data]) =>
              `#### ${variant}\n- Experiments: ${data.count}\n- Outcomes: ${Object.entries(data.outcomes).map(([outcome, count]) => `${outcome}: ${count}`).join(', ')}`
            ).join('\n\n')}

            ### Average Metrics
            ${Object.entries(summary.averageMetrics).map(([metric, value]) => `- ${metric}: ${value}`).join('\n')}

            ### Raw Data
            See attached summary file for complete data.

            ---
            *Generated automatically on ${summary.generatedAt}*
            `;

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Copilot Experiment Summary - ${month}`,
                body: issueBody,
                labels: ['copilot-experiments', 'monthly-summary']
              });
            } else {
              console.log('No summary file found for this month');
            }
