# ============================================================================
# Political Sphere - Docker CI/CD Pipeline
# Validates Docker infrastructure, builds images, runs security scans
# ============================================================================
# Tier: 1 (Operational Mandatory)
# Controls: SEC-01, SEC-05, QUAL-02, OPS-01
# Execution Mode: Safe
# ============================================================================

name: Docker CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/*/Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'scripts/dev-*.sh'
      - 'scripts/docker-*.sh'
      - 'scripts/seed-db.sh'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/*/Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'scripts/dev-*.sh'
      - 'scripts/docker-*.sh'
      - 'scripts/seed-db.sh'
      - '.github/workflows/docker.yml'
  workflow_dispatch:

# Cancel superseded runs for faster feedback and lower costs
concurrency:
  group: docker-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  IMAGE_PREFIX: political-sphere

# Scoped permissions at workflow level (jobs override as needed)
permissions:
  contents: read

jobs:
  # ============================================================================
  # Job 1: Validate Docker Compose Configuration
  # ============================================================================
  validate-compose:
    name: Validate Docker Compose
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate docker-compose.yml syntax
        run: |
          docker compose -f docker-compose.yml config > /dev/null
          echo "✓ Docker Compose syntax valid"

      - name: Check for exposed secrets
        run: |
          # Flag hard-coded secrets but allow ${...} env templates
          if grep -E ':\s*[^$][^"]+$' docker-compose.yml | grep -Ei '(password|secret|token|key)'; then
            echo "❌ Found potential hard-coded secret in docker-compose.yml"
            exit 1
          fi
          echo "✓ No exposed secrets found"

      - name: Validate service health checks
        run: |
          # Use Python for robust YAML parsing (no external dependencies)
          python3 - <<'PY'
          import yaml, sys
          with open('docker-compose.yml') as f:
              d = yaml.safe_load(f)
          services = d.get('services', {})
          must_have = ['postgres', 'redis', 'api', 'worker']
          missing = [s for s in must_have if 'healthcheck' not in services.get(s, {})]
          if missing:
              print(f"❌ Missing healthchecks for: {', '.join(missing)}")
              sys.exit(1)
          print("✓ All critical services have healthchecks")
          PY

  # ============================================================================
  # Job 2: Build and Test Docker Images
  # ============================================================================
  build-images:
    name: Build ${{ matrix.service }} Image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: validate-compose
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        service:
          - api
          - frontend
          - worker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build metadata
        run: echo "CREATED=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_PREFIX }}-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build image (test)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.service }}/Dockerfile
          target: production
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REVISION=${{ github.sha }}
            CREATED=${{ env.CREATED }}

      - name: Test image runs
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -1)
          echo "Testing image: $IMAGE_TAG"
          
          # Start container
          CONTAINER_ID=$(docker run -d \
            -e NODE_ENV=test \
            -e PORT=3000 \
            "$IMAGE_TAG")
          
          echo "Container started: $CONTAINER_ID"
          
          # Wait up to 30s for container to be ready
          timeout=30
          while [ $timeout -gt 0 ]; do
            if docker inspect "$CONTAINER_ID" --format='{{.State.Status}}' | grep -q running; then
              echo "✓ Container is running"
              break
            fi
            sleep 1
            timeout=$((timeout - 1))
          done
          
          # Show logs
          docker logs "$CONTAINER_ID"
          
          # Cleanup
          docker stop "$CONTAINER_ID"
          docker rm "$CONTAINER_ID"

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # ============================================================================
  # Job 3: Security Scanning with Trivy
  # ============================================================================
  security-scan:
    name: Security Scan ${{ matrix.service }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build-images
    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        service:
          - api
          - frontend
          - worker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build metadata
        run: echo "CREATED=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Build image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.service }}/Dockerfile
          target: production
          push: false
          load: true
          tags: ${{ matrix.service }}:scan
          cache-from: type=gha
          build-args: |
            REVISION=${{ github.sha }}
            CREATED=${{ env.CREATED }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ matrix.service }}:scan
          format: sarif
          output: trivy-results-${{ matrix.service }}.sarif
          severity: CRITICAL,HIGH
          exit-code: '0'
          cache: true

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results-${{ matrix.service }}.sarif
          category: trivy-docker-${{ matrix.service }}

      - name: Run Trivy for detailed report
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ matrix.service }}:scan
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          cache: true

  # ============================================================================
  # Job 4: Integration Test with Docker Compose
  # ============================================================================
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build-images

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          cat > .env << 'EOF'
          NODE_ENV=test
          POSTGRES_USER=testuser
          POSTGRES_PASSWORD=testpass
          POSTGRES_DB=testdb
          REDIS_PASSWORD=testredis
          KEYCLOAK_ADMIN=admin
          KEYCLOAK_ADMIN_PASSWORD=admin
          JWT_SECRET=test-jwt-secret-min-32-chars-required
          EOF

      - name: Start services with compose
        run: docker compose up -d postgres redis --wait --wait-timeout 180

      - name: Show status
        run: docker compose ps && docker compose logs --since=2m

      - name: Run status check script
        run: |
          chmod +x scripts/docker-status.sh
          ./scripts/docker-status.sh || true # Don't fail on missing optional services

      - name: Test database connection
        run: |
          docker compose exec -T postgres psql -U testuser -d testdb -c "SELECT version();"
          echo "✓ PostgreSQL connection successful"

      - name: Test Redis connection
        run: |
          docker compose exec -T redis redis-cli --pass testredis PING
          echo "✓ Redis connection successful"

      - name: Cleanup
        if: always()
        run: |
          docker compose down -v --remove-orphans
          docker compose ps

  # ============================================================================
  # Job 5: Validate Helper Scripts
  # ============================================================================
  validate-scripts:
    name: Validate Helper Scripts
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check script syntax
        run: |
          for script in scripts/dev-*.sh scripts/docker-*.sh scripts/seed-db.sh; do
            if [ -f "$script" ]; then
              echo "Checking $script..."
              bash -n "$script"
              echo "✓ $script syntax valid"
            fi
          done

      - name: Check script executability
        run: |
          for script in scripts/dev-*.sh scripts/docker-*.sh scripts/seed-db.sh; do
            if [ -f "$script" ]; then
              if [ ! -x "$script" ]; then
                echo "❌ $script is not executable"
                exit 1
              fi
            fi
          done
          echo "✓ All scripts are executable"

      - name: Test help flags
        run: |
          for script in scripts/dev-up.sh scripts/dev-down.sh scripts/docker-status.sh; do
            if [ -f "$script" ]; then
              echo "Testing $script --help..."
              "$script" --help
            fi
          done

  # ============================================================================
  # Job 6: Hadolint - Dockerfile Linting
  # ============================================================================
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        service:
          - api
          - frontend
          - worker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hadolint ${{ matrix.service }} Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: apps/${{ matrix.service }}/Dockerfile
          ignore: DL3018  # Allow apk add --no-cache without pinning

  # ============================================================================
  # Job 7: Semgrep - Code Security Scanning
  # ============================================================================
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write

    container:
      image: returntocorp/semgrep:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep
        run: semgrep scan --config=p/ci --sarif --output=semgrep.sarif || true
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload Semgrep results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
          category: semgrep

  # ============================================================================
  # Summary Job
  # ============================================================================
  docker-ci-summary:
    name: Docker CI Summary
    runs-on: ubuntu-latest
    if: always()
    needs:
      - validate-compose
      - build-images
      - security-scan
      - integration-test
      - validate-scripts
      - hadolint
      - semgrep

    steps:
      - name: Check job results
        run: |
          echo "=== Docker CI Pipeline Summary ==="
          echo "Validate Compose: ${{ needs.validate-compose.result }}"
          echo "Build Images: ${{ needs.build-images.result }}"
          echo "Security Scan: ${{ needs.security-scan.result }}"
          echo "Integration Test: ${{ needs.integration-test.result }}"
          echo "Validate Scripts: ${{ needs.validate-scripts.result }}"
          echo "Hadolint: ${{ needs.hadolint.result }}"
          echo "Semgrep: ${{ needs.semgrep.result }}"
          
          # Critical checks (must pass)
          if [ "${{ needs.validate-compose.result }}" != "success" ] || \
             [ "${{ needs.build-images.result }}" != "success" ] || \
             [ "${{ needs.integration-test.result }}" != "success" ] || \
             [ "${{ needs.validate-scripts.result }}" != "success" ]; then
            echo "❌ Pipeline failed - critical checks"
            exit 1
          fi
          
          # Optional checks (warning only)
          if [ "${{ needs.hadolint.result }}" != "success" ]; then
            echo "⚠️  Hadolint checks failed"
          fi
          if [ "${{ needs.semgrep.result }}" != "success" ]; then
            echo "⚠️  Semgrep checks failed"
          fi
          
          echo "✓ All critical checks passed"
