name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          while ! pg_isready -h localhost -p 5432; do
            sleep 1
          done

      - name: Initialize database
        run: |
          # Run database initialization if script exists
          if [ -f "scripts/init-database.js" ]; then
            node scripts/init-database.js || echo "Database init script not ready yet"
          else
            echo "Skipping database initialization - script not found"
          fi
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test

      - name: Seed test data
        run: |
          # Seed minimal test data if seed file exists
          if [ -f "scripts/seed/test-seed.sql" ]; then
            PGPASSWORD=test psql -h localhost -p 5432 -U test -d test -f scripts/seed/test-seed.sql
          else
            echo "Skipping seed data - test-seed.sql not found"
          fi

      - name: Start API service (if available)
        run: |
          if npm run | grep -q "start:api"; then
            npm run start:api &
            # Wait for service to be ready
            timeout 60 bash -c 'until curl -f http://localhost:4000/healthz 2>/dev/null; do sleep 1; done' || echo "API not ready"
          else
            echo "start:api script not found - skipping"
          fi

      - name: Start Frontend service (if available)
        run: |
          if npm run | grep -q "start:frontend"; then
            npm run start:frontend &
            # Wait for service to be ready  
            timeout 60 bash -c 'until curl -f http://localhost:3000 2>/dev/null; do sleep 1; done' || echo "Frontend not ready"
          else
            echo "start:frontend script not found - skipping"
          fi

      - name: Run integration tests
        run: npm run test:integration
        env:
          API_BASE_URL: http://localhost:4000
          FRONTEND_BASE_URL: http://localhost:3000
          DATABASE_URL: postgresql://test:test@localhost:5432/test

      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: test-results/
          retention-days: 30
