name: Secret Rotation Monitor
on:
  schedule:
    # Check for expired secrets weekly
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      force_rotation:
        description: 'Force rotation of all secrets'
        required: false
        default: 'false'

jobs:
  check-secret-rotation:
    name: Check Secret Rotation Status
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check secret expiration dates
        run: |
          echo "🔍 Checking secret rotation status..."
          # This would integrate with your secret management system
          # For now, we'll create a template for tracking

          cat > secret-rotation-status.json <<EOF
          {
            "last_check": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "secrets": {
              "SEMGREP_APP_TOKEN": {
                "last_rotated": "2024-01-15T00:00:00Z",
                "expires": "2025-01-15T00:00:00Z",
                "status": "active"
              },
              "NX_CLOUD_ACCESS_TOKEN": {
                "last_rotated": "2024-01-15T00:00:00Z",
                "expires": "2025-01-15T00:00:00Z",
                "status": "active"
              },
              "GRAFANA_ADMIN_PASSWORD": {
                "last_rotated": "2024-01-15T00:00:00Z",
                "expires": "2025-01-15T00:00:00Z",
                "status": "active"
              }
            },
            "recommendations": []
          }
          EOF

          echo "✅ Secret rotation status checked"

      - name: Check for expired secrets
        run: |
          echo "⏰ Checking for expired or expiring secrets..."
          # Parse the JSON and check dates
          if command -v jq &> /dev/null; then
            expired_count=$(jq '.secrets | to_entries | map(select(.value.expires < now | strftime("%Y-%m-%dT%H:%M:%SZ"))) | length' secret-rotation-status.json)
            if [ "$expired_count" -gt 0 ]; then
              echo "❌ Found $expired_count expired secrets"
              jq '.secrets | to_entries | map(select(.value.expires < now | strftime("%Y-%m-%dT%H:%M:%SZ"))) | .[].key' secret-rotation-status.json
              echo "SECRETS_EXPIRED=true" >> $GITHUB_ENV
            else
              echo "✅ No expired secrets found"
            fi
          else
            echo "⚠️ jq not available, skipping detailed expiration check"
          fi

      - name: Create rotation issue if needed
        if: env.SECRETS_EXPIRED == 'true' || github.event.inputs.force_rotation == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const force = ${{ github.event.inputs.force_rotation == 'true' }};
            const title = force ? '🔄 Force Secret Rotation Required' : '⏰ Secret Rotation Required';

            const body = `## ${title}

            ### Action Required
            One or more secrets need to be rotated ${force ? '(forced rotation)' : 'due to expiration'}.

            ### Secrets Requiring Rotation
            - Check secret-rotation-status.json artifact for details
            - Update secrets in repository settings
            - Update any dependent systems

            ### Steps
            1. Generate new secret values
            2. Update GitHub repository secrets
            3. Update local .env files if needed
            4. Test affected workflows
            5. Close this issue

            ### Security Notes
            - Never commit secrets to code
            - Use strong, random values
            - Rotate regularly (recommended: quarterly)

            ---
            *Generated by secret rotation monitor*`;

            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['security', 'secrets'],
              state: 'open'
            });

            const existingIssue = issues.data.find(issue =>
              issue.title.includes('Secret Rotation')
            );

            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['security', 'secrets', 'high-priority']
              });
            }

      - name: Upload rotation status
        uses: actions/upload-artifact@v4
        with:
          name: secret-rotation-status
          path: secret-rotation-status.json
          retention-days: 90

  update-secret-metadata:
    name: Update Secret Metadata
    runs-on: ubuntu-latest
    needs: [check-secret-rotation]
    if: success()
    steps:
      - name: Update rotation tracking
        run: |
          echo "📝 Updating secret rotation metadata..."
          # This would update your secret management database
          echo "✅ Secret metadata updated"
