name: Performance Budgets

on:
  push:
    branches: [main]

jobs:
  k6-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 smoke (skips if PERF_BASE_URL unset)
        run: |
          if [ -z "$PERF_BASE_URL" ]; then echo "PERF_BASE_URL not set; skipping."; exit 0; fi
          k6 run --summary-export artifacts/k6-summary.json scripts/perf/smoke.js

      - name: Check budgets
        run: |
          if [ ! -f artifacts/k6-summary.json ]; then echo "No k6 summary; skipping budgets check."; exit 0; fi
          SUMMARY_JSON=artifacts/k6-summary.json BUDGETS_JSON=apps/api/budgets.json node scripts/ci/check-budgets.mjs
