name: Smoke Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  smoke:
    name: Run smoke checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run smoke tests
        run: npm run test:smoke
