name: AI maintenance (index / cache)

on:
  push:
    branches: [main]
    paths:
      - 'scripts/ai/**'
      - 'ai-learning/**'
      - 'ai-cache/**'
      - '.github/workflows/**'
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  maintenance:
    name: AI maintenance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit

      - name: Build async code index
        run: |
          node ./scripts/ai/code-indexer.js build
        env:
          INDEXER_CONCURRENCY: 40

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install ANN dependencies
        run: |
          pip install hnswlib numpy flask

      - name: Build embeddings
        run: |
          node ./scripts/ai/embeddings.js build
        env:
          EMBED_DIMS: 128

      - name: Build ANN index
        run: |
          python3 scripts/ai/ann_service/build_and_serve.py build

      - name: Run smoke tests
        run: |
          chmod +x ./scripts/ai/smoke.sh
          ./scripts/ai/smoke.sh

      - name: Run pre-cache (FAST_AI=0)
        run: |
          node ./scripts/ai/pre-cache.js

      - name: Preload contexts
        run: |
          node ./scripts/ai/context-preloader.js preload

      - name: Run competence assessment
        run: |
          node ./scripts/ai/competence-monitor.js assess

      - name: Upload ai-index artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-index
          path: |
            ai-index/codebase-index.json
            ai-index/semantic-vectors.json
            ai-index/ann/

      - name: Upload ai-cache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-cache
          path: ai-cache/

      - name: Persist ai-index to branch
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH=ai-index-cache
          mkdir -p tmp_index
          cp -r ai-index tmp_index/ || true
          cd tmp_index
          git init
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          git fetch origin $BRANCH || true
          # Create or switch to branch
          git checkout -B $BRANCH || true
          git add ai-index || true
          if git diff --staged --quiet; then
            echo "No changes to index (including ANN artifacts) to commit"
          else
            git commit -m "chore: update ai-index with ANN artifacts (generated by ai-maintenance workflow)"
            git push origin $BRANCH --force
          fi
          cd ..
          rm -rf tmp_index
