# GitHub labeler configuration for automated PR labeling
# This file defines rules for automatically applying labels to pull requests
# based on the files that have been changed
# See: https://github.com/actions/labeler

ci:
  - changed-files:
      - any-glob-to-any-file: 'ci/**'

dev:
  - changed-files:
      - any-glob-to-any-file: 'dev/**'

docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

infrastructure:
  - changed-files:
      - any-glob-to-any-file: 'infrastructure/**'

platform:
  - changed-files:
      - any-glob-to-any-file: 'platform/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'package-lock.json'

github:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
