name: security-scan

on:
  workflow_call:
    inputs:
      working_directory:
        description: Path to scan (defaults to repo root)
        type: string
        default: '.'
      npm_audit:
        description: Run npm audit (true/false)
        type: boolean
        default: true
      trivy_config:
        description: Additional Trivy config flags
        type: string
        default: ''
      grype_config:
        description: Additional Grype config flags
        type: string
        default: ''
    secrets:
      gh_token:
        required: false
        description: GitHub token for authenticated dependency checks

jobs:
  scan:
    name: Security Scans
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (npm)
        if: inputs.npm_audit
        run: npm install --package-lock-only

      - name: npm audit
        if: inputs.npm_audit
        run: npm audit --audit-level high || true

      - name: Download Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Trivy filesystem scan
        run: |
          TRIVY_OPTS="${{ inputs.trivy_config }}"
          trivy fs --exit-code 1 --severity CRITICAL,HIGH ${TRIVY_OPTS} .

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Grype scan
        run: |
          GRYPE_OPTS="${{ inputs.grype_config }}"
          grype "dir:${{ github.workspace }}/${{ inputs.working_directory }}" --fail-on high ${GRYPE_OPTS}
